name: Pull Request Checks

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'bot-service/**'

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./bot-service

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version-file: 'bot-service/.python-version'
        cache: 'pip'

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -

    - name: Configure Poetry
      run: |
        poetry config virtualenvs.create true
        poetry config virtualenvs.in-project true

    - name: Cache Poetry dependencies
      uses: actions/cache@v3
      with:
        path: bot-service/.venv
        key: ${{ runner.os }}-poetry-${{ hashFiles('bot-service/poetry.lock') }}

    - name: Install dependencies
      run: poetry install --no-root

    - name: Run linting
      run: |
        poetry run flake8 .
        poetry run black . --check
        poetry run isort . --check

    - name: Run tests
      run: poetry run pytest --cov-report=xml
